# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

jobs:
  run-playwright-tests:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - run:
          name: "Install Dependencies"
          command: npm install
      - run:
          name: "Run Playwright Tests on BrowserStack"
          command: npx browserstack-node-sdk playwright test

  say-hello:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

workflows:
  test-workflow:
    jobs:
      - run-playwright-tests
      - say-hello
